#include "theme.h"

#include <QApplication>

namespace Theme {

struct ColorEntry {
    ColorRole role;
    const char* hex;
};

static const ColorEntry kColors[] = {
    { Background,          "#1e1e1e" },
    { BackgroundSecondary, "#252526" },
    { BackgroundTertiary,  "#2d2d2d" },
    { Foreground,          "#d4d4d4" },
    { Border,              "#3a3a3a" },
    { Selection,           "#264f78" },
    { Accent,              "#264f78" },
    { AlternateRow,        "#252526" },
    { HexAltRow,           "#1a1a1a" },
    { HexOffset,           "#858585" },
    { HexText,             "#d4d4d4" },
    { HexCursor,           "#3a3a3a" },
    { HexSelection,        "#264f78" },
    { HexDiff,             "#5c1e1e" },
    { Keyword,             "#569cd6" },
    { Type,                "#4ec9b0" },
    { String,              "#ce9178" },
    { Number,              "#b5cea8" },
    { Comment,             "#6a9955" },
    { Error,               "#f44336" },
    { ScrollBar,           "#424242" },
    { ScrollBarHover,      "#4f4f4f" },
};

QColor color(ColorRole role)
{
    for (const auto& c : kColors) {
        if (c.role == role)
            return QColor(c.hex);
    }
    return QColor("#ffffff");
}

QString stylesheet()
{
    const QString bg    = color(Background).name();
    const QString bg2   = color(BackgroundSecondary).name();
    const QString bg3   = color(BackgroundTertiary).name();
    const QString fg    = color(Foreground).name();
    const QString bdr   = color(Border).name();
    const QString sel   = color(Selection).name();
    const QString alt   = color(AlternateRow).name();
    const QString scr   = color(ScrollBar).name();
    const QString scrH  = color(ScrollBarHover).name();

    return QString(
        "QMainWindow, QDockWidget {\n"
        "    background: %1;\n"
        "    color: %2;\n"
        "}\n"
        "QMenuBar {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border-bottom: 1px solid %4;\n"
        "}\n"
        "QMenuBar::item:selected {\n"
        "    background: %5;\n"
        "}\n"
        "QMenu {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "}\n"
        "QMenu::item:selected {\n"
        "    background: %5;\n"
        "}\n"
        "QStatusBar {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border-top: 1px solid %4;\n"
        "}\n"
        "QDockWidget::title {\n"
        "    background: %3;\n"
        "    padding: 2px 6px;\n"
        "    text-align: left;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QDockWidget::close-button, QDockWidget::float-button {\n"
        "    background: %3;\n"
        "    padding: 0px;\n"
        "}\n"
        "QTextEdit, QPlainTextEdit {\n"
        "    background: %1;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    selection-background-color: %5;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QTableView {\n"
        "    background: %1;\n"
        "    color: %2;\n"
        "    gridline-color: %4;\n"
        "    selection-background-color: %5;\n"
        "    selection-color: %2;\n"
        "    border: none;\n"
        "    alternate-background-color: %6;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QTableView::item:selected {\n"
        "    background: %5;\n"
        "    color: %2;\n"
        "}\n"
        "QTableView::item:focus {\n"
        "    background: %5;\n"
        "    color: %2;\n"
        "}\n"
        "QHeaderView::section {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: none;\n"
        "    border-bottom: 1px solid %4;\n"
        "    padding: 2px 6px;\n"
        "    font-weight: bold;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QScrollBar:vertical, QScrollBar:horizontal {\n"
        "    background: %1;\n"
        "    border: none;\n"
        "}\n"
        "QScrollBar::handle {\n"
        "    background: %7;\n"
        "    border-radius: 2px;\n"
        "    min-height: 14px;\n"
        "    min-width: 14px;\n"
        "}\n"
        "QScrollBar::handle:hover {\n"
        "    background: %8;\n"
        "}\n"
        "QScrollBar::add-line, QScrollBar::sub-line {\n"
        "    background: none;\n"
        "    border: none;\n"
        "}\n"
        "QProgressBar {\n"
        "    background: %1;\n"
        "    border: 1px solid %4;\n"
        "    border-radius: 2px;\n"
        "    text-align: center;\n"
        "    color: %2;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QProgressBar::chunk {\n"
        "    background: %5;\n"
        "    border-radius: 3px;\n"
        "}\n"
        "QMessageBox {\n"
        "    background: %3;\n"
        "}\n"
        "QMessageBox QLabel {\n"
        "    color: %2;\n"
        "}\n"
        "QMessageBox QPushButton {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    padding: 2px 8px;\n"
        "}\n"
        "QTabWidget::pane {\n"
        "    border: 1px solid %4;\n"
        "    background: %1;\n"
        "    top: -1px;\n"
        "}\n"
        "QTabBar::tab {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    padding: 3px 10px;\n"
        "    border: 1px solid %4;\n"
        "    margin-right: 1px;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QTabBar::tab:selected {\n"
        "    background: %1;\n"
        "    border-bottom: 1px solid %1;\n"
        "}\n"
        "QTabBar::tab:hover:!selected {\n"
        "    background: %4;\n"
        "}\n"
        "QLineEdit {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    padding: 2px 4px;\n"
        "    selection-background-color: %5;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QPushButton {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    padding: 2px 8px;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "    background: %4;\n"
        "}\n"
        "QPushButton:pressed {\n"
        "    background: %5;\n"
        "    color: #ffffff;\n"
        "}\n"
        "QToolTip {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    padding: 4px;\n"
        "}\n"
        "QSplitter::handle {\n"
        "    background: %4;\n"
        "}\n"
        "QSplitter::handle:horizontal {\n"
        "    width: 2px;\n"
        "}\n"
        "QSplitter::handle:vertical {\n"
        "    height: 2px;\n"
        "}\n"
        "QDialog {\n"
        "    background: %1;\n"
        "    color: %2;\n"
        "}\n"
        "QLabel {\n"
        "    color: %2;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QCheckBox {\n"
        "    color: %2;\n"
        "    font-size: 11px;\n"
        "    spacing: 6px;\n"
        "}\n"
        "QCheckBox::indicator {\n"
        "    width: 14px;\n"
        "    height: 14px;\n"
        "    border: 1px solid %4;\n"
        "    background: %3;\n"
        "    border-radius: 2px;\n"
        "}\n"
        "QCheckBox::indicator:checked {\n"
        "    background: %5;\n"
        "    border: 1px solid %5;\n"
        "}\n"
        "QCheckBox::indicator:hover {\n"
        "    border: 1px solid %5;\n"
        "}\n"
        "QRadioButton {\n"
        "    color: %2;\n"
        "    font-size: 11px;\n"
        "    spacing: 6px;\n"
        "}\n"
        "QRadioButton::indicator {\n"
        "    width: 14px;\n"
        "    height: 14px;\n"
        "    border: 1px solid %4;\n"
        "    background: %3;\n"
        "    border-radius: 7px;\n"
        "}\n"
        "QRadioButton::indicator:checked {\n"
        "    background: %5;\n"
        "    border: 1px solid %5;\n"
        "}\n"
        "QSpinBox, QDoubleSpinBox {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    padding: 2px 4px;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QSpinBox::up-button, QDoubleSpinBox::up-button,\n"
        "QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
        "    background: %3;\n"
        "    border: 1px solid %4;\n"
        "    width: 14px;\n"
        "}\n"
        "QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover,\n"
        "QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover {\n"
        "    background: %4;\n"
        "}\n"
        "QComboBox {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    padding: 2px 8px;\n"
        "    font-size: 11px;\n"
        "}\n"
        "QComboBox::drop-down {\n"
        "    border: none;\n"
        "    width: 20px;\n"
        "}\n"
        "QComboBox::down-arrow {\n"
        "    image: none;\n"
        "    border-left: 4px solid transparent;\n"
        "    border-right: 4px solid transparent;\n"
        "    border-top: 5px solid %2;\n"
        "    width: 0px;\n"
        "    height: 0px;\n"
        "}\n"
        "QComboBox QAbstractItemView {\n"
        "    background: %3;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    selection-background-color: %5;\n"
        "}\n"
        "QGroupBox {\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    margin-top: 8px;\n"
        "    padding-top: 8px;\n"
        "    font-size: 11px;\n"
        "    font-weight: bold;\n"
        "}\n"
        "QGroupBox::title {\n"
        "    subcontrol-origin: margin;\n"
        "    left: 6px;\n"
        "    padding: 0 4px;\n"
        "}\n"
        "QSlider::groove:horizontal {\n"
        "    background: %4;\n"
        "    height: 4px;\n"
        "    border-radius: 2px;\n"
        "}\n"
        "QSlider::sub-page:horizontal {\n"
        "    background: %5;\n"
        "    height: 4px;\n"
        "    border-radius: 2px;\n"
        "}\n"
        "QSlider::add-page:horizontal {\n"
        "    background: %4;\n"
        "    height: 4px;\n"
        "    border-radius: 2px;\n"
        "}\n"
        "QSlider::handle:horizontal {\n"
        "    background: %2;\n"
        "    width: 12px;\n"
        "    margin: -4px 0;\n"
        "    border-radius: 6px;\n"
        "}\n"
        "QListView, QListWidget, QTreeView, QTreeWidget {\n"
        "    background: %1;\n"
        "    color: %2;\n"
        "    border: 1px solid %4;\n"
        "    selection-background-color: %5;\n"
        "    selection-color: %2;\n"
        "    font-size: 11px;\n"
        "    outline: 0;\n"
        "}\n"
        "QTreeView::item, QListView::item {\n"
        "    padding: 2px 4px;\n"
        "}\n"
        "QTreeView::branch {\n"
        "    background: %1;\n"
        "}\n"
    ).arg(bg, fg, bg3, bdr, sel, alt, scr, scrH);
}

void applyToApplication()
{
    if (qApp)
        qApp->setStyleSheet(stylesheet());
}

} // namespace Theme
